# Matrices and Vectors

Matrices are 2-dimensional arrays:

\begin{bmatrix} a & b & c \newline d & e & f \newline g & h & i \newline j & k & l\end{bmatrix}

The above matrix has four rows and three columns, so it is a 4 x 3 matrix.

A vector is a matrix with one column and many rows:

\begin{bmatrix} w \newline x \newline y \newline z \end{bmatrix}

So vectors are a subset of matrices. The above vector is a 4 x 1 matrix.

Notation and terms:

* $A_{ij}$ refers to the element in the ith row and jth column of matrix A.

* A vector with 'n' rows is referred to as an 'n'-dimensional vector.

* $v_i$ refers to the element in the ith row of the vector.

* With python, all our vectors and matrices will be 0-indexed. Note that for some programming languages, the arrays are 1-indexed.

* Matrices are usually denoted by uppercase names while vectors are lowercase.

* "Scalar" means that an object is a single value, not a vector or matrix.

* $\mathbb{R}$ refers to the set of scalar real numbers.

* $\mathbb{R^n}$ refers to the set of n-dimensional vectors of real numbers.





## Matrices & Vectors with Python

Python doesn't have a built-in type for matrices. However, we can treat a list of lists as a matrix. For example:

In [11]:
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [12]:
print("A =", A) 
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row
column = [];        # empty list
for row in A:
  column.append(row[2])   
print("3rd column =", column)

A = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
A[1] = [4, 5, 6]
A[1][2] = 6
A[0][-1] = 3
3rd column = [3, 6, 9, 12]


Using nested lists as a matrix works for simple computational tasks, however, there is a better way of working with matrices in Python using NumPy package.



## NumPy

NumPy is a package for scientific computing which has support for a powerful N-dimensional array object.
NumPy provides multidimensional array of numbers (which is actually an object). Let's take an example:



In [63]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("A = ")
print(A)              
print("type of A =",type(A)) 

A = 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
type of A = <class 'numpy.ndarray'>


In [35]:
# Initialize a matrix 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Initialize a vector 
v = np.array([1, 2, 3])
              
# Get the dimension of the matrix A where m = rows and n = columns
[m,n] = A.shape
print("The dimension of matrix A is: {},{}".format(m,n))

# You could also store it this way
dim_A = A.shape
print("The dimension of matrix A is: {}".format(dim_A))

# Get the dimension of the vector v 
dim_v = v.shape
print("The dimension of vector v is: {}".format(dim_v))

# Now let's index into the 2nd row 3rd column of matrix A
A_12 = A[1,2]
print("A_12 = {}".format(A_12))


The dimension of matrix A is: 4,3
The dimension of matrix A is: (4, 3)
The dimension of vector v is: (3,)
A_12 = 6


# Matrix Addition and Scalar Multiplication

Addition and subtraction are element-wise, so you simply add or subtract each corresponding element:

\begin{equation}
\begin{bmatrix} a & b \newline c & d \newline \end{bmatrix} + \begin{bmatrix} w & x \newline y & z \newline \end{bmatrix} =\begin{bmatrix} a+w & b+x \newline c+y & d+z \newline \end{bmatrix}
\end{equation}

Subtracting Matrices:

\begin{equation}
\begin{bmatrix} a & b \newline c & d \newline \end{bmatrix} - \begin{bmatrix} w & x \newline y & z \newline \end{bmatrix} =\begin{bmatrix} a-w & b-x \newline c-y & d-z \newline \end{bmatrix}
\end{equation}

To add or subtract two matrices, their dimensions must be the same.

In scalar multiplication, we simply multiply every element by the scalar value:

\begin{equation}
\begin{bmatrix} a & b \newline c & d \newline \end{bmatrix} * x =\begin{bmatrix} a*x & b*x \newline c*x & d*x \newline \end{bmatrix}
\end{equation}

In scalar division, we simply divide every element by the scalar value:

\begin{equation}
\begin{bmatrix} a & b \newline c & d \newline \end{bmatrix} / x =\begin{bmatrix} a /x & b/x \newline c /x & d /x \newline \end{bmatrix}
\end{equation}



### Addition and Scalar Multiplication with Python


In [60]:
# Initialize matrix A and B 
A = np.array([[1, 2, 4], [5, 3, 2]])
B = np.array([[1, 3, 4], [1, 1, 1]])

# Initialize constant s 
s = 2

# See how element-wise addition works
add_AB = A + B 
print("\n add_AB = ")
print(add_AB)

# See how element-wise subtraction works
sub_AB = A - B
print("\n sub_AB = ")
print(sub_AB)

# See how scalar multiplication works
mult_As = A * s
print("\n mult_As = ")
print(mult_As)

# Divide A by s
div_As = A / s
print("\n div_As = ")
print(div_As)

# What happens if we have a Matrix + scalar?
add_As = A + s
print("\n add_As = ")
print(add_As)



 add_AB = 
[[2 5 8]
 [6 4 3]]

 sub_AB = 
[[ 0 -1  0]
 [ 4  2  1]]

 mult_As = 
[[ 2  4  8]
 [10  6  4]]

 div_As = 
[[0.5 1.  2. ]
 [2.5 1.5 1. ]]

 add_As = 
[[3 4 6]
 [7 5 4]]


# Matrix-Vector Multiplication

We map the column of the vector onto each row of the matrix, multiplying each element and summing the result.

\begin{equation}
\begin{bmatrix} a & b \newline c & d \newline e & f \end{bmatrix} *\begin{bmatrix} x \newline y \newline \end{bmatrix} =\begin{bmatrix} a*x + b*y \newline c*x + d*y \newline e*x + f*y\end{bmatrix}
\end{equation}

The result is a **vector**. The number of **columns** of the matrix must equal the number of **rows** of the vector.

An **m x n matrix** multiplied by an **n x 1 vector** results in an **m x 1 vector**.

Below is an example of a matrix-vector multiplication. Make sure you understand how the multiplication works. Feel free to try different matrix-vector multiplications.

In [65]:
# Initialize matrix A 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Initialize vector v
v = np.array([[1], [2], [3]])

# Multiply A * B
Av = np.matmul(A, v)
print("\n Av = ")
print(Av)


 Av = 
[[14]
 [32]
 [50]]


# Matrix-Matrix Multiplication

We multiply two matrices by breaking it into several vector multiplications and concatenating the result.

\begin{equation}
\begin{bmatrix} a & b \newline c & d \newline e & f \end{bmatrix} *\begin{bmatrix} w & x \newline y & z \newline \end{bmatrix} =\begin{bmatrix} a*w + b*y & a*x + b*z \newline c*w + d*y & c*x + d*z \newline e*w + f*y & e*x + f*z\end{bmatrix}
\end{equation}

An **m x n matrix** multiplied by an **n x o matrix** results in an **m x o matrix**. In the above example, a 3 x 2 matrix times a 2 x 2 matrix resulted in a 3 x 2 matrix.

To multiply two matrices, the number of **columns** of the first matrix must equal the number of **rows** of the second matrix.

For example:


In [61]:
# Initialize matrix A 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Initialize matrix B
B = np.array([[1, 2], [3, 4], [5, 6]])

# Multiply A * B
AB = np.matmul(A, B)
print("\n AB = ")
print(AB)



 AB = 
[[ 22  28]
 [ 49  64]
 [ 76 100]]


## Matrix Multiplication Properties

* Matrices are not commutative: A∗B≠B∗A
* Matrices are associative: (A∗B)∗C=A∗(B∗C)

The identity matrix, when multiplied by any matrix of the same dimensions, results in the original matrix. It's just like multiplying numbers by 1. The identity matrix simply has 1's on the diagonal (upper left to lower right diagonal) and 0's elsewhere.

\begin{bmatrix} 1 & 0 & 0 \newline 0 & 1 & 0 \newline 0 & 0 & 1 \newline \end{bmatrix}

When multiplying the identity matrix after some matrix (A∗I), the square identity matrix's dimension should match the other matrix's columns. When multiplying the identity matrix before some other matrix (I∗A), the square identity matrix's dimension should match the other matrix's rows.



In [70]:
# Initialize random matrices A and B 
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 1], [0, 2]])

# Initialize a 2 by 2 identity matrix
I = np.eye(2)

# The above notation is the same as I = [1,0;0,1]

# What happens when we multiply I*A ? 
IA = np.matmul(I,A)
print("\n IA = ")
print(IA)

# How about A*I ? 
AI = np.matmul(A,I)
print("\n AI = ")
print(AI)

# Compute A*B 
AB = np.matmul(A,B) 
print("\n AB = ")
print(AB)

# Is it equal to B*A? 
BA = np.matmul(B,A)
print("\n BA = ")
print(BA)

# Note that IA = AI but AB != BA


 IA = 
[[1. 2.]
 [3. 4.]]

 AI = 
[[1. 2.]
 [3. 4.]]

 AB = 
[[ 1  5]
 [ 3 11]]

 BA = 
[[4 6]
 [6 8]]


# Matrix Inverse and Transpose

The **inverse** of a matrix $A$ is denoted $A^{-1}$.
Multiplying by the inverse results in the identity matrix.

A non-square matrix does not have an inverse matrix. We can compute inverses of matrices in python with the `np.linalg.inv(A)` function. 
Matrices that don't have an inverse are singular or degenerate.

The **transposition** of a matrix is like rotating the matrix 90° in the clockwise direction and then reversing it. We can compute transposition of matrices in python with the `np.matrix.transpose(A)` function:

In [81]:
# Initialize matrix A 
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])

# Transpose A 
A_trans = np.matrix.transpose(A) 
print("\n A_trans = ")
print(A_trans)

# Take the inverse of A 
A_inv = np.linalg.inv(A)
print("\n A_inv = ")
print(A_inv)

# What is A^(-1)*A? 
A_invA = np.matmul(A_inv,A)
print("\n A_invA = ")
print(A_invA)


 A_trans = 
[[1 4 7]
 [2 0 8]
 [3 6 9]]

 A_inv = 
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]

 A_invA = 
[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
